---
title: "Introduction to how to use Normalisation Package"
author: "Mark Cheng"
date: "09/11/2023"
output:
  html_document: 
    theme: cerulean
    toc: yes
    toc_float: yes
#Unorthodox calling in a vignette: did not use standard output of html_vignette (which is simpler but more space efficient), but rather traditional .rmd html_document format.
#This is because this is not uploaded to CRAN. see more details here (https://bookdown.org/yihui/rmarkdown/r-package-vignette.html).

---
## Setting up
load the library/package from github.
```{r setup}
if(!require("devtools"))install.packages("devtools",repos="http://cran.us.r-project.org")
devtools::install_github("TKMarkCheng/NormaliseForIC50")
```

```{r}
input_file <- "../Validation/2022-09-04 reads/example1.xlsx" #CHANGE to example file in your directory
input_directory = "../Validation/2022-09-04 reads/" #CHANGE this to directory of input .xlsx data files
output_file <- "../Validation/test.xlsx" # CHANGE directory and name for yourself 
rotate_by <- 0 # clockwise degrees, multiples of 90, useful when doing 12 fold dilutions.
```
## Getting the filenames from our directory
What are the names of all of our input files?
```{r get all the filepaths in the directory}
neut_raw_files <- Sys.glob(paste0(
  paste0(input_directory,"*.xlsx")) # find all .xlsx file in input directory
)
neut_raw_files
```
## Example case: Plate 1
An inital view of plate 1
```{r example}
plate1 <- NormaliseForIC50::read_promega_plate_excel(input_promega_excel_file_path = "../Validation/2022-09-04 reads/example1.xlsx")
plate1
```
The Name assigned to each column can be any string of characters, as long as there's no excessively weird symbols.

```{r test run}
NormaliseForIC50::final_func(neut_raw_files[1],rotation_deg_needed = rotate_by)
```
## Processing all the files in the directory

```{r}
#create xlsx and populate df into separate sheets. CHANGE rotation_deg_needed if the plate was ROTATED when setting up.
library(openxlsx)
wb<-createWorkbook()
for (neut_raw_file in neut_raw_files){
  neut_file <- basename(neut_raw_file) #remove file path
  neut_file = tools::file_path_sans_ext(neut_file) #remove extension
  addWorksheet(wb,sheetName=neut_file)
  writeData(wb, sheet = neut_file,
            x = NormaliseForIC50::final_func(
              neut_raw_file,rotation_deg_needed = rotate_by))
  print(paste0("normalised data written to:",neut_file))
}
saveWorkbook(wb,file=output_file,overwrite = TRUE)
print(paste0("saved collated sheets to excel file:",output_file))
```
